/* eslint-disable max-len */
const DataBirds = [
    {
      family: 'Разминка',
      data: [
        {
          id: 1,
          name: 'Волнистый попугай',
          species: 'Melopsittacus undulatus',
          description: 'Особи отличаются шумом и болтливостью, довольно легко запоминают слова и выражения, которые повторяют много раз при «общении» с человеком и даже с другими домашними птицами. В большинстве случаев заученные слова и выражения повторяют без связной логики. Населяют полупустынные и степные местности, предпочитая участки с редкими деревьями. Эти попугайчики стремительны в полёте и изящны в движениях, хорошо ходят по земле и лазают по деревьям. Живут стаями. Стаи могут насчитывать от 20 до нескольких сот особей.',
          image: 'http://zoogalaktika.ru/assets/images/aves/psittaciformes/melopsittacus-undulatus/melopsittacus-undulatus_01.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/EHGWCIGILC/XC335525-budgerigar-snp1.mp3',
        },
        {
          id: 2,
          name: 'Кошка',
          species: 'Felis catus',
          description: 'Домашнее животное, одно из наиболее популярных (наряду с собакой) «животных-компаньонов». С точки зрения научной систематики, домашняя кошка — млекопитающее семейства кошачьих отряда хищных. Ранее домашнюю кошку нередко рассматривали как отдельный биологический вид. С точки зрения современной биологической систематики домашняя кошка является подвидом лесной кошки',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/carnivora/felidae/felis-silvestris-catus/felis-silvestris-catus_09.jpg',
          audio: 'https://zvukipro.com/uploads/files/2017-08/1504025531_myaukane_koshki_-_myaukane_koshki.mp3',
        },
        {
          id: 3,
          name: 'Колибри',
          species: 'Trochilidae',
          description: 'В основном позывки колибри состоят из короткого слога продолжительностью около одной секунды и немного более длинного — до двух секунд. Некоторые виды используют более продолжительную мелодию.',
          image: 'https://live.staticflickr.com/4667/39803446184_4c51fd5997_c.jpg',
          audio: 'https://www.xeno-canto.org/469239/download',
        },
        {
          id: 4,
          name: 'Корова',
          species: 'vitula eligans',
          description: 'оте­лив­шая­ся сам­ка круп­но­го ро­га­то­го ско­та, то есть домашнего быка. Прежде, чем стать коровой, самка быка является тёлкой (до первого оплодотворения), после оплодотворения до первых родов она называется нетелью.Коровы используются для получения потомства, а также молочной и мясной продукции',
          image: 'http://zoogalaktika.ru/assets/images/easy/pictures/cow_01.jpg',
          audio: 'https://zvukipro.com/uploads/files/2020-07/1595395371_dd699f7949bfe19.mp3',
        },
        {
          id: 5,
          name: 'Овца',
          species: 'Ovis aries',
          description: 'Парнокопытное млекопитающее из рода баранов, семейства полорогих. Это животное уже в глубокой древности было одомашнено человеком, в основном благодаря густой шерсти и съедобному мясу.',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/artiodactyla/ruminantia/caprinae/ovis-aries/ovis-aries_05.jpg',
          audio: 'https://zvukipro.com/uploads/files/2017-09/1504342524_zvuki-baranov-i-ovec.mp3',
        },
        {
          id: 6,
          name: 'Беркут',
          species: 'Aquila chrysaetos',
          description: 'Одна из самых известных и наиболее широко распространённых хищных птиц в северном полушарии, беркут является крупным пернатым хищником, размах крыльев которого достигает 2,34 метра.',
          image: 'https://bugaga.ru/uploads/posts/2016-10/1476967577_hischnye-pticy-5.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC572763-Kungs%C3%B6rn_05.mp3',
        },
      ],
    },
    {
      family: 'Попугаи и другие',
      data: [
        {
          id: 1,
          name: 'Волнистый попугай',
          species: 'Melopsittacus undulatus',
          description: 'Особи отличаются шумом и болтливостью, довольно легко запоминают слова и выражения, которые повторяют много раз при «общении» с человеком и даже с другими домашними птицами. В большинстве случаев заученные слова и выражения повторяют без связной логики. Населяют полупустынные и степные местности, предпочитая участки с редкими деревьями. Эти попугайчики стремительны в полёте и изящны в движениях, хорошо ходят по земле и лазают по деревьям. Живут стаями. Стаи могут насчитывать от 20 до нескольких сот особей.',
          image: 'http://zoogalaktika.ru/assets/images/aves/psittaciformes/melopsittacus-undulatus/melopsittacus-undulatus_01.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/EHGWCIGILC/XC335525-budgerigar-snp1.mp3',
        },
        {
          id: 2,
          name: 'Неразлучники',
          species: 'Agapornis',
          description: 'Издавна этих попугаев называли неразлучниками, так как считали, что при гибели одной птицы, другая вскоре погибает от тоски.',
          image: 'https://live.staticflickr.com/3068/3389640204_73874536fb_c.jpg',
          audio: 'https://www.xeno-canto.org/422306/download',
        },
        {
          id: 3,
          name: 'Какаду',
          species: 'Cacatuidae',
          description: 'Очень привязываются к человеку, который заботится о них и уделяет им много внимания. Хотя они не обладают большими способностями к разговору, их можно научить произносить несколько десятков слов и даже небольшие фразы, издавать самые разнообразные звуки. Так как какаду обладают очень высокими интеллектуальными способностями, они легко обучаются различным командам и трюкам. ',
          image: 'https://live.staticflickr.com/65535/49144787166_ecbed74428_c.jpg',
          audio: 'https://www.xeno-canto.org/446593/download',
        },
        {
          id: 4,
          name: 'Канарейка',
          species: 'Serinus canaria',
          description: 'Канарейка может отличать последовательности звуков, хранить в памяти и воспроизводить. Поэтому она может научиться присущему виду пению. Она может подражать звукам и последовательностям звуков других птиц, а также включать чужие шумы в своё пение.',
          image: 'http://zoogalaktika.ru/assets/images/aves/passeriformes/fringillidae/serinus-canaria/small/serinus-canaria_small_01.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/JXZFXAZWHY/XC485630-kanarek.mp3',
        },
        {
          id: 5,
          name: 'Корелла',
          species: 'Nymphicus hollandicus',
          description: 'лина с хвостом 30—33 см, а сам хвост 14—16 см; вес около 100 г. Характерной чертой является довольно высокий хохолок на голове и длинный заострённый хвост. Окраска оперения у самцов и самок разная. Самец окрашен более ярко. Оперение у него тёмно-оливково-серое, хохолок и голова жёлтые. ',
          image: 'https://pet7.ru/wp-content/uploads/2017/04/popugaj-korella.jpg',
          audio: 'https://www.xeno-canto.org/446593/download',
        },
        {
          id: 6,
          name: 'Прыгающий попугай',
          species: 'Cyanoramphus',
          description: 'Это маленькие, живущие на земле попугаи, которые хорошо маскируются благодаря зелёному цвету оперения. Своё название получили из-за своего обитания в нижнем ярусе леса, где они быстро бегают по земле, разыскивая корм в лесной подстилке, разгребая её примерно так же, как это делают домашние куры.',
          image: 'http://popugay.crimea.ua/vidi/img/cyanoramphus-auriceps.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/BPSDQEOJWG/Red-fronted_Parakeet_locklate_Les_Grandes_Fongeres_Farino_2009-07-04.mp3',
        },
      ],
    },
    {
      family: 'Домашние животные',
      data: [
        {
          id: 1,
          name: 'Собака',
          species: 'Canis lupus familiaris',
          description: 'Предки собак – это древние волки и другие представители псовых, возможно, шакалы. От них ей досталось достаточно крепкое мускулистое тело, покрытое шерстью. Форма и размер головы собак является определяющим экстерьерным признаком, по которому собаку можно отнести к той или иной породе.',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/carnivora/canidae/canis-familiaris/canis-familiaris_01.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/canis-familiaris.mp3',
        },
        {
          id: 2,
          name: 'Кошка',
          species: 'Felis catus',
          description: 'Домашнее животное, одно из наиболее популярных (наряду с собакой) «животных-компаньонов». С точки зрения научной систематики, домашняя кошка — млекопитающее семейства кошачьих отряда хищных. Ранее домашнюю кошку нередко рассматривали как отдельный биологический вид. С точки зрения современной биологической систематики домашняя кошка является подвидом лесной кошки',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/carnivora/felidae/felis-silvestris-catus/felis-silvestris-catus_09.jpg',
          audio: 'https://zvukipro.com/uploads/files/2017-08/1504025531_myaukane_koshki_-_myaukane_koshki.mp3',
        },
        {
          id: 3,
          name: 'Корова',
          species: 'vitula eligans',
          description: 'оте­лив­шая­ся сам­ка круп­но­го ро­га­то­го ско­та, то есть домашнего быка. Прежде, чем стать коровой, самка быка является тёлкой (до первого оплодотворения), после оплодотворения до первых родов она называется нетелью.Коровы используются для получения потомства, а также молочной и мясной продукции',
          image: 'http://zoogalaktika.ru/assets/images/easy/pictures/cow_01.jpg',
          audio: 'https://zvukipro.com/uploads/files/2020-07/1595395371_dd699f7949bfe19.mp3',
        },
        {
          id: 4,
          name: 'Кролик',
          species: 'Lepus',
          description: 'Кролики отличаются от зайцев альтрициальностью  — их детёныши рождаются слепыми, лишёнными мехового покрова, растут в норах. Кролики обладают полными, овальными телами. Их уши достигают длины более 10 см, возможно, являются адаптацией к обнаружению хищников, также для охлаждения тела. ',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/lagomorpha/oryctolagus-cuniculus/oryctolagus-cuniculus_03.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/oryctolagus-cuniculus.mp3',
        },
        {
          id: 5,
          name: 'Петух',
          species: 'Gallus',
          description: 'Петух — символ задирчивости и крови. У некоторых народов до сих пор существуют петушиные бои. У восточных славян и в христианской мифологии одна из важнейших функций петуха как предвестника — часовая. Его спев означает начало нового часа, когда действуют тёмные бесовские силы. Своим спевом спевший петух разгоняет нечисть до следующей ночи. Спев третьих петухов — знак ровной продолжительности полночи до утренней зари — свидетельствует о завершении действия нечистых сил. Славяне при строительстве дома приносили в жертву чёрного петуха.',
          image: 'http://zoogalaktika.ru/assets/images/aves/galliformes/phasianidae/gallus-gallus-domesticus/gallus-gallus-domesticus_02.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/gallus-2.mp3',
        },
        {
          id: 6,
          name: 'Морская свинка',
          species: ' Cavia porcellus',
          description: 'вид одомашненных грызунов из рода свинок семейства свинковых. Несмотря на название, не связаны ни с семейством свиней, ни с Гвинеей, а также не являются морскими животными. Были одомашнены инками и использовались в качестве источника ценного мяса, а также в декоративных целях[. По одной из версий, происходят от кутлеровой свинки. Оба предполагаемых предка живут в Перу.',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/rodentia/cavia-porcellus/cavia-porcellus_05.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/cavia-porcellus.mp3',
        },
      ],
    },
    {
      family: 'Экзотические птицы',
      data: [
        {
          id: 1,
          name: 'Птица-носорог',
          species: 'Bucerotidae',
          description: 'Птицы-носороги получили своё название из-за больших длинных клювов, резко загнутых вниз и имеющих у своего основания значительные выросты различной формы, которые отсутствуют лишь у представителей рода токи',
          image: 'http://live.staticflickr.com/65535/49515334681_685fbe7d24_b.jpg',
          audio: 'https://www.xeno-canto.org/460480/download',
        },
        {
          id: 2,
          name: 'Тукан',
          species: 'Ramphastos toco',
          description: 'У большого тукана необыкновенное оперение: тело его черное, воротник, грудь и верхняя часть хвоста белые, а нижняя часть хвоста красная. Но самым выдающимся у него является гигантский желто-оранжевый клюв с красной частью сверху и черным пятном на конце. ',
          image: 'https://live.staticflickr.com/4640/24382801737_f945490027_k.jpg',
          audio: 'https://www.xeno-canto.org/506060/download',
        },
        {
          id: 3,
          name: 'Турако',
          species: 'Tauraco',
          description: 'Турако — это длиннохвостые птицы, достигающие длины от 35 до 45 см. У них имеется прямой хохол из перьев на голове. Окраска оперения чаще металлически зелёная и синяя. Самец и самка в пределах своего вида не имеют отличий в окраске и размере. ',
          image: 'https://live.staticflickr.com/65535/49492671063_85d8ee6aa2_c.jpg',
          audio: 'https://www.xeno-canto.org/345104/download',
        },
        {
          id: 4,
          name: 'Красный ибис',
          species: 'Eudocimus ruber',
          description: 'Красный ибис живёт в больших группах, насчитывающих часто по несколько сотен сородичей. Его питание состоит из насекомых, моллюсков, крабов и рыб. Своим серповидным согнутым вниз клювом он ковыряется в мягкой тине, отыскивая червей и крабов.',
          image: 'https://live.staticflickr.com/8767/17943230879_66eb50e9c4_c.jpg',
          audio: 'https://www.xeno-canto.org/222844/download',
        },
        {
          id: 5,
          name: 'Колибри',
          species: 'Trochilidae',
          description: 'В основном позывки колибри состоят из короткого слога продолжительностью около одной секунды и немного более длинного — до двух секунд. Некоторые виды используют более продолжительную мелодию.',
          image: 'https://live.staticflickr.com/4667/39803446184_4c51fd5997_c.jpg',
          audio: 'https://www.xeno-canto.org/469239/download',
        },
        {
          id: 6,
          name: 'Танагра-медосос',
          species: 'Cyanerpes caeruleus',
          description: 'Пурпурная танагра-медосос часто образует маленькие группы. Питается нектаром, ягодами и насекомыми, преимущественно в кроне деревьев. Охотно отвечает на призыв рыжего воробьиного сыча.',
          image: 'https://live.staticflickr.com/4358/37375722256_fcd613ee1f_c.jpg',
          audio: 'https://www.xeno-canto.org/512306/download',
        },
      ],
    },
    {
      family: 'Фермерские животные',
      data: [
        {
          id: 1,
          name: 'Курица',
          species: 'Gallus domesticus',
          description: 'Cамая многочисленная и распространённая домашняя птица, которая является одомашненной формой банкивской джунглевой курицы. Летает плохо, недалеко. Разводят их ради мяса и яиц, кроме того, от них получают перо и пух.',
          image: 'https://live.staticflickr.com/670/21535633069_9a36b98aca_k.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/gallus.mp3',
        },
        {
          id: 2,
          name: 'Овца',
          species: 'Ovis aries',
          description: 'Парнокопытное млекопитающее из рода баранов, семейства полорогих. Это животное уже в глубокой древности было одомашнено человеком, в основном благодаря густой шерсти и съедобному мясу.',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/artiodactyla/ruminantia/caprinae/ovis-aries/ovis-aries_05.jpg',
          audio: 'https://zvukipro.com/uploads/files/2017-09/1504342524_zvuki-baranov-i-ovec.mp3',
        },
        {
          id: 3,
          name: 'Индейка',
          species: 'Meleagris gallopavo',
          description: 'Дикая индейка служит предметом охоты как ружейной (к самцам подкрадываются на току, то есть в брачный период), так и ловушками. Последняя облегчается крайней глупостью птицы.',
          image: 'https://live.staticflickr.com/4591/38669218274_4e39d328e6_k.jpg',
          audio: 'http://www.xeno-canto.org/370486/download',
        },
        {
          id: 4,
          name: 'Осел',
          species: 'Equus asinus asinus',
          description: ' одомашненный подвид дикого осла, сыгравший важную историческую роль в развитии хозяйства и культуры человека и по-прежнему широко распространённый (более 40 миллионов) в хозяйстве многих развивающихся стран. Небольшое количество ослов содержится для разведения или в качестве домашних животных в развитых странах. Осёл использовался в качестве рабочего животного не менее 5000 лет.',
          image: 'http://zoogalaktika.ru/assets/images/easy/pictures/ass_03.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/ass.mp3',
        },
        {
          id: 5,
          name: 'Утка',
          species: 'Anas platyrhynchos',
          description: 'Породы домашних уток подразделяются на мясные (пекинские, серые украинские, чёрные белогрудые), мясо-яичные (зеркальные, хаки-кемпбелл), яичные (индийские бегуны). Уток разводят во многих странах, в том числе в России.',
          image: 'https://live.staticflickr.com/3873/15296687926_911fd18ab3_k.jpg',
          audio: 'http://www.xeno-canto.org/525303/download',
        },
        {
          id: 6,
          name: 'Свинья',
          species: 'Suidae',
          description: 'семейство нежвачных парнокопытных, включающее 8 видов, в том числе единственного европейского представителя семейства — дикого кабана, который является прародителем домашней свиньи. Детёныш свиньи называется поросёнком.',
          image: 'http://zoogalaktika.ru/assets/images/mammalia/artiodactyla/nonruminantia/suidae/sus-scrofa-domesticus/sus-scrofa-domesticus_01.jpg',
          audio: 'http://zoogalaktika.ru/assets/images/media/sounds/sus-scrofa.mp3',
        },
      ],
    },
    {
      family: 'Крупные птицы',
      data: [
        {
          id: 1,
          name: 'Журавли',
          species: 'Grus',
          description: 'род птиц семейства настоящих журавлей, обитающих в Европе, Азии, Северной Америке и Австралии. Все виды так или иначе связаны с водными, главным образом, заболоченными территориями.',
          image: 'https://moscowseasons.com/uploads/2019/12/03/5de6249a3b54c.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/IIJAXHKSCC/XC584673-Wattled%20Crane%20(call%20in%20flight)%2020200722,BangweuluWetlands,ZAMBIA.mp3',
        },
        {
          id: 2,
          name: 'Страус',
          species: 'Struthio camelus',
          description: 'бескилевая нелетающая птица, единственный современный представитель семейства страусовых.',
          image: 'https://animalreader.ru/wp-content/uploads/2013/03/straus-samaja-bolshaja-ptica-v-mire_1.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/YTUXOCTUEM/XC516153-Struthio_camelus_australis-FL%20quiet%20calls%20imm%20Polokwane%20GameRes%2030Oct19%208.05am%20LS115271a.mp3',
        },
        {
          id: 3,
          name: 'Чёрный гриф',
          species: 'Aegypius monachus',
          description: 'Это очень крупные птицы, общая длина тела которых достигает 1 м, размер крыла - 85 см, вес - 7-12 кг. Несмотря на название, оперение грифа не черное, а серовато-бурое. Только у молодых особей до года свойственен черный оттенок.',
          image: 'http://flashsiberia.com/sites/default/files/styles/780x450/public/uploads/main/grif.jpg?itok=VujjNpk8',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/UXGZWVYDFE/XC144935-Aegypius%20monachus_pos%C3%A9_C_F%20Deroussen_2013042300.mp3',
        },
        {
          id: 4,
          name: 'Беркут',
          species: 'Aquila chrysaetos',
          description: 'Одна из самых известных и наиболее широко распространённых хищных птиц в северном полушарии, беркут является крупным пернатым хищником, размах крыльев которого достигает 2,34 метра.',
          image: 'https://bugaga.ru/uploads/posts/2016-10/1476967577_hischnye-pticy-5.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC572763-Kungs%C3%B6rn_05.mp3',
        },
        {
          id: 5,
          name: 'Боевой орёл',
          species: 'Polemaetus bellicosus',
          description: 'Обитающий в открытых и полуоткрытых местах Африки южнее Сахары, боевой орёл является очень крупной птицей, средняя длина которой достигает 96 сантиметров, размах крыльев — до 260 сантиметров, а вес — до 6,2 килограмма.',
          image: 'https://bugaga.ru/uploads/posts/2016-10/1476967612_hischnye-pticy-10.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/IOBXPIMNNC/XC459351-181203_0176.mp3',
        },
        {
          id: 6,
          name: 'Филин',
          species: 'Bubo bubo',
          description: 'Имеющего размах крыльев до 190 сантиметров, филина иногда называют самой крупной в мире совой. Обитающий в основном в горных районах, хвойных лесах и степях, филин является ночным хищником, который охотится на целый ряд различных хищных видов, преимущественно мелких млекопитающих, а также на других птиц, рептилий, земноводных, рыб, крупных насекомых и различных беспозвоночных.',
          image: 'https://bugaga.ru/uploads/posts/2016-10/1476967643_hischnye-pticy-6.jpg',
          audio: 'https://www.xeno-canto.org/sounds/uploaded/WNLIDKJKXT/XC518386-sense%20t%C3%ADtol.mp3',
        },
      ],
    },
  ];
  
  export default DataBirds;